version: "3"
name: esgi-cluster

services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    restart: always
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./:/app


  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_MEMORY=4g
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./:/app



  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_MEMORY=4g
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./:/app


  spark-worker-3:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_MEMORY=4g
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      - ./:/app
