version: '3'

services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "8081:8081"
    depends_on:
      - spark-master

  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "8082:8081"
    depends_on:
      - spark-master

  spark-worker-3:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-3
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    ports:
      - "8083:8081"
    depends_on:
      - spark-master
